variables:
  LCG_REL_PATH: /cvmfs/sft.cern.ch/lcg/views/LCG_104a_cuda/x86_64-centos8-gcc11-opt
  GIT_SUBMODULE_STRATEGY: recursive
  PYTHONIOENCODING: "utf-8"

image: gitlab-registry.cern.ch/ci-tools/ci-worker:cs8

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH == "for_release"

stages:
  - build
  - test
  - deploy

compile:
  stage: build
  before_script:
    - source $LCG_REL_PATH/setup.sh
    - eval $(make env)
  script:
    - make -j 4
    - pushd externals/HiggsAnalysis/CombinedLimit
    - export CONDA=1 CONDA_PREFIX=$LCG_REL_PATH
    - make -j 8; make
    - popd
    #- pushd externals
    #- curl -L https://github.com/microsoft/onnxruntime/releases/download/v1.15.1/onnxruntime-linux-x64-1.15.1.tgz | tar xzv
    #- popd
  artifacts:
    paths:
      - lib
      - python/**/*.pyc
      - externals/HiggsAnalysis/CombinedLimit/build/bin
      - externals/HiggsAnalysis/CombinedLimit/build/lib
      #- externals/onnxruntime-linux-x64-1.15.1

code-checks:
  stage: build
  before_script:
    - yum install -y clang-tools-extra
    - source $LCG_REL_PATH/setup.sh
    - eval $(make env)
  script:
    - make code-format
    - git diff --exit-code --numstat --
    - make py-checks | tee py-checks.log
  allow_failure: true

run-tests:
  stage: test
  before_script:
    - yum install -y libSM
    - source $LCG_REL_PATH/setup.sh
    - eval $(make env)
    - ./gitlab-ci/do_kinit.sh
    - cd examples
  script:
    - make
  artifacts:
    paths:
      - plots
    when: always