variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PYTHONIOENCODING: "utf-8"

.el8-106a:
  image: gitlab-registry.cern.ch/sft/docker/alma8
  variables:
    LCG_REL_PATH: /cvmfs/sft.cern.ch/lcg/views/LCG_106a_cuda/x86_64-el8-gcc11-opt
    LIBS_EXTRA: ""

.el9-106a:
  image: gitlab-registry.cern.ch/sft/docker/alma9
  variables:
    LCG_REL_PATH: /cvmfs/sft.cern.ch/lcg/views/LCG_106a_cuda/x86_64-el9-gcc11-opt
    LIBS_EXTRA: ""

.el9-dev3:
  image: gitlab-registry.cern.ch/sft/docker/alma9
  variables:
    LCG_REL_PATH: /cvmfs/sft.cern.ch/lcg/views/dev3/latest/x86_64-el9-gcc13-opt
    LIBS_EXTRA: ""    

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "web"

stages:
  - build
  - test
  - test2
  - deploy

.compile:
  tags: [ k8s-cvmfs ]
  stage: build
  before_script:
    - '[[ "$LIBS_EXTRA" != "" ]] && yum install -y $LIBS_EXTRA'
    - source $LCG_REL_PATH/setup.sh || true
    - eval $(make env)
  script:
    - make -j 4
    - pushd externals/HiggsAnalysis/CombinedLimit
    - export LCG=1
    - make -j 8; make
    - popd
    - pushd externals
    - curl -L https://github.com/microsoft/onnxruntime/releases/download/v1.18.1/onnxruntime-linux-x64-1.18.1.tgz
    - popd
  artifacts:
    paths:
      - lib
      - python/**/*.pyc
      - externals/HiggsAnalysis/CombinedLimit/build/bin
      - externals/HiggsAnalysis/CombinedLimit/build/lib
      - externals/onnxruntime-linux-x64-1.18.1

compile-el8-106a:
  extends: [.compile, .el8-106a]

compile-el9-106a:
  extends: [.compile, .el9-106a]

compile-el9-dev3:
  extends: [.compile, .el9-dev3]

code-checks:
  tags: [ k8s-cvmfs ]
  image: gitlab-registry.cern.ch/linuxsupport/alma9-base
  stage: build
  before_script:
    - dnf install -qy clang-tools-extra git-core make perl python3-pip which
    - python3 -mpip install autopep8 flake8
  script:
    - make code-format
    - git diff -u > code-format.patch
    - git diff --exit-code --numstat --
    - make py-checks | tee py-checks.log
  allow_failure: true
  artifacts:
    expose_as: 'code-format patch'
    paths:
      - code-format.patch
    when: always

code-checks-dev3:
  extends: code-checks
  image: gitlab-registry.cern.ch/sft/docker/alma9
  before_script:
    - source /cvmfs/sft.cern.ch/lcg/views/dev3/latest/x86_64-el9-gcc13-opt/setup.sh || true
    - source /cvmfs/cms.cern.ch/el9_amd64_gcc13/external/llvm/17.0.3-668a2da8722f50b3ef72a74c2282af69/etc/profile.d/init.sh
  artifacts:
    expose_as: 'code-format patch dev3'
    paths:
      - code-format-dev3.patch
    when: always

.run-tests:
  tags: [ k8s-cvmfs ]
  stage: test
  before_script:
    - '[[ "$LIBS_EXTRA" != "" ]] && yum install -y $LIBS_EXTRA'
    - source $LCG_REL_PATH/setup.sh || true
    - eval $(make env)
    - ./gitlab-ci/do_kinit.sh
    - cd examples
  script:
    - python3 run_simple_mc_nanoAOD.py
    - echo
    - echo ---------------------------------
    - python3 run_simple_data_ttH.py
    - echo
    - echo ---------------------------------
    - python3 run_simpleCache_sos.py
    - echo
    - echo ---------------------------------
    - python3 run_simpleCache_sos.py # second time
    - echo
    - echo ---------------------------------
    - python3 run_friends_sos.py
    - echo
    - echo ---------------------------------
    - python3 run_uncertainties_ttH.py -j 4
    - echo
    - echo --------------------
    - echo "Comparing to references"
    - "sha256sum -c ref/refs-base.txt --quiet && echo 'All outputs match references'"
  artifacts:
    paths:
      - examples/plots
    when: always
  timeout: 2h

.run-tests-base-el8-106a:
  extends: [.run-tests, .el8-106a]
  needs: [compile-el8-106a]

.run-tests-base-el9-106a:
  extends: [.run-tests, .el9-106a]
  needs: [compile-el9-106a]

.run-tests-base-el9-dev3:
  extends: [.run-tests, .el9-dev3]
  needs: [compile-el9-dev3]

.run-tests-cards:
  extends: .run-tests
  script:
    - python3 run_datacards_ttV_ttHH_2018c.py
    - echo
    - echo --------------------
    - echo "Comparing to references"
    - "sha256sum -c ref/refs-cards-prefit.txt --quiet && echo 'prefit outputs match'"
    - "sha256sum -c ref/refs-cards-cards.txt --quiet && echo 'datacards match'"
    - "sha256sum -c ref/refs-cards-postfit.txt --quiet && echo 'postfit outputs match' || true"

.run-tests-cards-el8-106a:
  extends: [.run-tests-cards, .el8-106a]
  needs: [compile-el8-106a]

.run-tests-cards-el9-106a:
  extends: [.run-tests-cards, .el9-106a]
  needs: [compile-el9-106a]

.run-tests-cards-el9-dev3:
  extends: [.run-tests-cards, .el9-dev3]
  needs: [compile-el9-dev3]

.run-tests-SFs:
  extends: .run-tests
  script:
    - python3 run_SFs_ttHH_2018c.py -j 8
    - echo
    - echo --------------------
    - echo "Comparing to references"
    - "sha256sum -c ref/refs-SF.txt --quiet && echo 'Outputs match'"

.run-tests-SFs-el8-106a:
  extends: [.run-tests-SFs, .el8-106a]
  needs: [compile-el8-106a]

.run-tests-SFs-el9-106a:
  extends: [.run-tests-SFs, .el9-106a]
  needs: [compile-el9-106a]

.run-tests-SFs-el9-dev3:
  extends: [.run-tests-SFs, .el9-dev3]
  needs: [compile-el9-dev3]


.run-tests-snapshot:
  extends: .run-tests
  script:
    - echo ---------------------------------
    - python3 run_snapshots_ttHH_2018c.py
    - echo
    - echo ---------------------------------
    - python3 run_snapshots_ttHH_2018c.py
    - echo
    - echo --------------------
    - echo "Comparing to references"
    - "sha256sum -c ref/refs-snapshot.txt --quiet && echo 'Outputs match'"

.run-tests-snapshot-el8-106a:
  extends: [.run-tests-snapshot, .el8-106a]
  needs: [compile-el8-106a]

.run-tests-snapshot-el9-106a:
  extends: [.run-tests-snapshot, .el9-106a]
  needs: [compile-el9-106a]

.run-tests-snapshot-el9-dev3:
  extends: [.run-tests-snapshot, .el9-dev3]
  needs: [compile-el9-dev3]

.run-tests-dask-base:
  extends: [.run-tests]
  stage: test
  variables:
    SCRIPT: run_distributed_ttHH_2018c.py
    REF: ref/refs-dist.txt
    CHECKOPTS: ""
    JOBS: 4
    LOCAL: false
    DASKLOCAL: true
    DASK: true
  script:
    - >
      if $LOCAL; then
        echo "--------------------";
        echo "Local";
        python3 $SCRIPT -n -j $JOBS local || exit 1;
        sha256sum -c $REF --quiet $CHECKOPTS && echo 'All outputs match' || exit 1;
      fi
    - >
      if $DASKLOCAL; then
        echo "--------------------";
        echo "On internal dask";
        python3 $SCRIPT -n -j $JOBS dask | grep -v '% Completed' || exit 1;
        sha256sum -c $REF --quiet $CHECKOPTS && echo 'All outputs match' || exit 1;
      fi
    - >
      if $DASK; then
        echo "--------------------";
        echo "On external dask";
        ( dask scheduler --port 11111 --no-dashboard --idle-timeout 30s > dasklog.txt 2>&1  & );
        sleep 3s
        ( dask worker tcp://localhost:11111 --nworkers $JOBS --nthreads 1 --memory-limit 2GB > workerlog.txt 2>&1 & );
        python3 $SCRIPT -n -j $JOBS dask -c tcp://localhost:11111 | grep -v '% Completed' || exit 1;
        sha256sum -c $REF --quiet $CHECKOPTS && echo 'All outputs match' || exit 1;
      fi
  timeout: 20m
  artifacts:
    paths:
      - examples/plots
      - examples/dasklog.txt
      - examples/workerlog.txt
    when: always

run-tests-dask-base-el9-dev3:
  extends: [.run-tests-dask-base, .el9-dev3]
  needs: [compile-el9-dev3]
  variables:
    SCRIPT: run_distributed_ttHH_2018c.py
    REF: ref/refs-dist.txt
    LOCAL: true

run-tests-dask-vary-el9-dev3:
  extends: [.run-tests-dask-base, .el9-dev3]
  needs: [compile-el9-dev3]
  variables:
    SCRIPT: run_uncertainties_ttH.py
    REF: ref/refs-base.txt
    CHECKOPTS: "--ignore-missing"

run-tests-dask-corrlib-el9-dev3:
  extends: [.run-tests-dask-base, .el9-dev3]
  needs: [compile-el9-dev3]
  variables:
    SCRIPT: run_SFs_ttHH_2018c.py
    REF: ref/refs-FS.txt
    CHECKOPTS: "--ignore-missing"
    DASKLOCAL: false

