name: cmgrdf
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - _x86_64-microarch-level=3
  - adwaita-icon-theme=49.0
  - anyio=4.13.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.3.0
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - attrs=26.1.0
  - babel=2.18.0
  - backports.zstd=1.3.0
  - beautifulsoup4=4.14.3
  - binutils=2.45.1
  - binutils_impl_linux-64=2.45.1
  - binutils_linux-64=2.45.1
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - boost=1.85.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - c-compiler=1.11.0
  - ca-certificates=2026.2.25
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2026.2.25
  - cffi=2.0.0
  - cfitsio=4.6.3
  - charset-normalizer=3.4.7
  - comm=0.2.3
  - compilers=1.11.0
  - conda-gcc-specs=14.3.0
  - cpython=3.12.13
  - cxx-compiler=1.11.0
  - davix=0.8.10
  - dbus=1.16.2
  - debugpy=1.8.20
  - decorator=5.2.1
  - defusedxml=0.7.1
  - epoxy=1.5.10
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - fastjet-cxx=3.5.1
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.17.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fortran-compiler=1.11.0
  - fqdn=1.5.1
  - freetype=2.14.3
  - fribidi=1.0.16
  - ftgl=2.4.0
  - gcc=14.3.0
  - gcc_impl_linux-64=14.3.0
  - gcc_linux-64=14.3.0
  - gdk-pixbuf=2.44.6
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gfortran=14.3.0
  - gfortran_impl_linux-64=14.3.0
  - gfortran_linux-64=14.3.0
  - giflib=5.2.2
  - gl2ps=1.4.2
  - glew=2.3.0
  - glib-tools=2.86.4
  - graphite2=1.3.14
  - graphviz=14.1.2
  - gsl=2.7
  - gsoap=2.8.123
  - gtest=1.17.0
  - gtk3=3.24.43
  - gts=0.7.6
  - gxx=14.3.0
  - gxx_impl_linux-64=14.3.0
  - gxx_linux-64=14.3.0
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=12.2.0
  - hicolor-icon-theme=0.17
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.8.0
  - importlib_resources=7.0.0
  - ipykernel=7.2.0
  - ipyparallel=9.1.0
  - ipython=9.12.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.14.0
  - jsonpointer=3.1.1
  - jsonschema=4.26.0
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.26.0
  - jupyter-lsp=2.3.1
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.4
  - jupyterlab=4.5.6
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.3
  - krb5=1.22.2
  - lark=1.3.1
  - ld_impl_linux-64=2.45.1
  - lerc=4.1.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.11.0
  - libboost=1.85.0
  - libboost-devel=1.85.0
  - libboost-headers=1.85.0
  - libboost-python=1.85.0
  - libboost-python-devel=1.85.0
  - libcblas=3.11.0
  - libcups=2.3.3
  - libcurl=8.19.0
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libegl-devel=1.7.0
  - libev=4.33
  - libexpat=2.7.5
  - libffi=3.5.2
  - libfreetype=2.14.3
  - libfreetype6=2.14.3
  - libgcc=15.2.0
  - libgcc-devel_linux-64=14.3.0
  - libgcc-ng=15.2.0
  - libgd=2.3.3
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libgl-devel=1.7.0
  - libglib=2.86.4
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libglx-devel=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.4.1
  - liblapack=3.11.0
  - libllvm20=20.1.8
  - liblzma=5.8.3
  - liblzma-devel=5.8.3
  - libnghttp2=1.68.1
  - libnsl=2.0.1
  - libopenblas=0.3.32
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.57
  - librsvg=2.60.2
  - libsanitizer=14.3.0
  - libsodium=1.0.21
  - libsqlite=3.53.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=14.3.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.42
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxml2-devel=2.15.1
  - libzlib=1.3.2
  - llvm-openmp=22.1.3
  - llvmlite=0.47.0
  - lz4-c=1.10.0
  - markupsafe=3.0.3
  - matplotlib-inline=0.2.1
  - metakernel=1.0.0
  - mistune=3.2.0
  - nbclient=0.10.4
  - nbconvert-core=7.17.1
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.12.0
  - notebook=7.5.5
  - notebook-shim=0.2.4
  - numba=0.65.0
  - numpy=2.4.3
  - openssl=3.6.2
  - overrides=7.7.0
  - packaging=26.0
  - pandocfilters=1.5.0
  - pango=1.56.4
  - parso=0.8.6
  - pcre=8.45
  - pcre2=10.47
  - pexpect=4.9.0
  - pip=26.0.1
  - pixman=0.46.4
  - platformdirs=4.9.6
  - portalocker=3.2.0
  - prometheus_client=0.25.0
  - prompt-toolkit=3.0.52
  - psutil=7.2.2
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.20.0
  - pygraphviz=1.14
  - pysocks=1.7.1
  - pythia8=8.312
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-gil=3.12.13
  - python-json-logger=2.0.7
  - python-tzdata=2026.1
  - python_abi=3.12
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - readline=8.3
  - referencing=0.37.0
  - requests=2.33.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - root=6.38.04
  - root_base=6.38.04
  - root_cxx_standard=20
  - rpds-py=0.30.0
  - scitokens-cpp=1.4.0
  - send2trash=2.1.0
  - setuptools=82.0.1
  - siscone=3.1.2
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.8.3
  - stack_data=0.6.3
  - sysroot_linux-64=2.17
  - tbb=2022.3.0
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.4.1
  - tornado=6.5.5
  - tqdm=4.67.3
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025c
  - uri-template=1.3.0
  - urllib3=2.6.3
  - vdt=0.4.4
  - vector-classes=1.4.5
  - wayland=1.25.0
  - wcwidth=0.6.0
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.46.3
  - xkeyboard-config=2.47
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.13
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.7
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxfixes=6.0.2
  - xorg-libxft=2.3.9
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.6
  - xorg-libxpm=3.5.18
  - xorg-libxrandr=1.5.5
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.7
  - xorg-xorgproto=2025.1
  - xrootd=5.9.2
  - xxhash=0.8.3
  - xz=5.8.3
  - xz-gpl-tools=5.8.3
  - xz-tools=5.8.3
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.2
  - zstd=1.5.7
  - pip:
    - PyYAML==6.0.1
    - Pygments==2.20.0
    - annotated-doc==0.0.4
    - annotated-types==0.7.0
    - asdf==3.2.0
    - asdf_standard==1.1.1
    - asdf_transform_schemas==0.5.0
    - attrs==23.2.0
    - awkward==2.9.0
    - awkward_cpp==52
    - boost-histogram==1.5.2
    - click==8.3.2
    - contourpy==1.2.1
    - correctionlib==2.8.0
    - cramjam==2.8.3
    - cycler==0.12.1
    - dacite==1.8.1
    - decaylanguage==0.18.3
    - fonttools==4.53.0
    - fsspec==2024.6.1
    - graphviz==0.20.3
    - hepstats==0.8.1
    - hepunits==2.3.4
    - hist==2.8.1
    - histoprint==2.4.0
    - iminuit==2.29.1
    - jmespath==1.0.1
    - kiwisolver==1.4.5
    - lark==1.1.9
    - markdown-it-py==4.0.0
    - matplotlib==3.9.0
    - mdurl==0.1.2
    - mkdocs-embed-external-markdown==3.0.2
    - mkdocs-multirepo-plugin==0.8.3
    - mplhep==0.3.59
    - mplhep_data==0.0.4
    - mypy-extensions==1.0.0
    - numpy==2.0.0
    - ordered-set==4.1.0
    - pandas==2.2.2
    - particle==0.25.1
    - pillow==10.4.0
    - pip-review==1.3.0
    - plothist==1.4.0
    - plothist_utils==0.0.1
    - plumbum==1.8.3
    - pydantic==2.12.5
    - pydantic_core==2.41.5
    - pylhe==0.9.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - python-slugify==8.0.4
    - pytz==2024.1
    - resample==1.10.0
    - rich==13.9.4
    - rich-tools==0.5.1
    - scipy==1.14.0
    - semantic-version==2.10.0
    - shellingham==1.5.4
    - six==1.16.0
    - text-unidecode==1.3
    - tqdm==4.66.4
    - traceback-with-variables==2.2.0
    - typer==0.24.1
    - typing-inspect==0.8.0
    - typing-inspection==0.4.2
    - typing_extensions==4.15.0
    - tzdata==2024.1
    - uhi==0.4.0
    - uproot==5.7.3
    - vector==1.5.1
    - xgboost==2.1.0
    - xxhash==3.6.0
    - zipp==3.19.2
